config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cerfacs-globc/idownscale:
      branch: master
      repo: https://github.com/cerfacs-globc/idownscale.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cerfacs-globc/idownscale git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-violet-termite.sh
        container: qc.acc_shaggy-wisteria-setter
  QC.Doc:
    repos:
      github.com/cerfacs-globc/idownscale find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-apricot-sheepdog.sh
        container: qc.doc_grumpy-jade-collie
      github.com/cerfacs-globc/idownscale git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-coral-hummingbird.sh
        container: qc.doc_lousy-puce-wolf
      github.com/cerfacs-globc/idownscale markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-viridian-badger.sh
        container: qc.doc_stealthy-emerald-markhor
  QC.Lic:
    repos:
      github.com/cerfacs-globc/idownscale licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-bistre-greyhound.sh
        container: qc.lic_bumpy-tan-kangaroo
  QC.Met:
    repos:
      github.com/cerfacs-globc/idownscale cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-pear-impala.sh
        container: qc.met_whiny-brass-sheep
  QC.Sec:
    repos:
      github.com/cerfacs-globc/idownscale bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-apricot-bison.sh
        container: qc.sec_slaphappy-plum-fossa
  QC.Sty:
    repos:
      github.com/cerfacs-globc/idownscale flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-xanthic-bonobo.sh
        container: qc.sty_dorky-periwinkle-fly
      github.com/cerfacs-globc/idownscale jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cinnabar-guppy.sh
        container: qc.sty_woozy-alizarin-heron
  QC.Uni:
    repos:
      github.com/cerfacs-globc/idownscale pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-persimmon-akbash.sh
        container: qc.uni_flaky-cerulean-dragon
  QC.Ver:
    repos:
      github.com/cerfacs-globc/idownscale get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-maroon-duck.sh
        container: qc.ver_hasty-platinum-quetzal
timeout: 5400
